name: Package WordPress Plugin

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Package for WordPress
      run: |
        zip -r throwaway-lookup.zip . \
          -x "tests/*" \
          -x "bin/*" \
          -x ".git/*" \
          -x ".github/*" \
          -x "./phpunit.xml.dist" \
          -x "*.zip"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: wordpress-plugin-package
        path: throwaway-lookup.zip